# Generated by Django 5.1.4 on 2025-01-11 20:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0004_readinggroup"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReadingSprint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("start_date", models.DateField(default=django.utils.timezone.now)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "chapters",
                    models.CharField(
                        blank=True,
                        help_text="Example: 'Chapters 1–3' or 'Pages 10–25' or 'Block A'",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed explanation of what this sprint covers and why.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sprints",
                        to="books.readinggroup",
                    ),
                ),
            ],
        ),
    ]
