# Generated by Django 5.1.4 on 2025-01-13 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0007_sprintidea_ideadiscussion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="cover",
            field=models.ImageField(
                blank=True, default="covers/default_cover.jpg", upload_to="covers/"
            ),
        ),
    ]
