# Generated by Django 5.1.4 on 2025-01-13 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0008_alter_book_cover"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default="2025-01-01T00:00:00Z"
            ),
            preserve_default=False,
        ),
    ]
