# Generated by Django 5.1.4 on 2025-01-13 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0009_book_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="HeroSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="Welcome to the Book Club!", max_length=100
                    ),
                ),
                (
                    "subtitle",
                    models.TextField(
                        default="Discover new books, join reading groups, and share your insights."
                    ),
                ),
                (
                    "background",
                    models.ImageField(
                        blank=True, null=True, upload_to="hero_backgrounds/"
                    ),
                ),
            ],
        ),
    ]
